from models.summarize_settings import Summarize_Settings


class Genshin_settings(Summarize_Settings):
    def __init__(
            self,
            thread_list_url='http://tarte.2ch.sc/gamesm/subback.html',
            thread_base_url='http://tarte.2ch.sc/test/read.cgi/gamesm/',
            thread_titel_format='原神総合スレ Part\d+',
            logs_dir='genshin',
            thd_soft_range=100,
            thd_soft_score_th=0.68,
            vectrize_model_name='sentence-transformers/paraphrase-multilingual-mpnet-base-v2',
            k_class_model_path='./logs/models/gr_ban_model_7c.pickle',
            soft_bans=[6, 5, 3, ],
            hard_bans=[6, 5, 3, ],
            topic_th=7,
            template_file_path='./html/basic_thread_page.html',
            wordpress_url='',
            wordpress_user='',
            wordpress_password='',
            wordpress_categorie_slugs=['genshin', ],
            wordpress_tag_slugs=[],
            save_outputs=False,
            base_logs_dir='./logs',
            wordpress_default_page_status='draft',
            wordpress_default_featured_media_id=None,
            candidate_media_metas=None,
            ng_word_file_title_path='./data/ng_words/genshin_title.txt',
            ng_word_file_page_path='./data/ng_words/genshin_page.txt',
            ng_word_file_parent_path='./data/ng_words/genshin_title.txt',
            ng_word_file_keyphrase_path='./data/ng_words/genshin_keyphrase.txt',
            post_notification_url=None,
            use_ng_title=False,
            use_ng_content=True,
            title_prefix='【原神】',
            title_suffix='',
        ):
        if wordpress_default_featured_media_id is None and candidate_media_metas is None:
            candidate_media_metas = {
                'main': [
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-1',
                        'title': '原神',
                        'alt_text': '原神',
                        'caption': '原神',
                        'description': '原神',
                        'words': [],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-2',
                        'title': '原神',
                        'alt_text': '原神',
                        'caption': '原神',
                        'description': '原神',
                        'words': [],
                    },
                ],
                'sub': [
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-3',
                        'title': 'ウェンティ',
                        'alt_text': 'ウェンティ',
                        'caption': 'ウェンティ',
                        'description': 'ウェンティ',
                        'words': ['ウェンティ'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-4',
                        'title': '甘雨',
                        'alt_text': '甘雨',
                        'caption': '甘雨',
                        'description': '甘雨',
                        'words': ['甘雨'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-5',
                        'title': '荒瀧一斗',
                        'alt_text': '荒瀧一斗',
                        'caption': '荒瀧一斗',
                        'description': '荒瀧一斗',
                        'words': ['荒瀧一斗', '荒瀧', '荒滝', '一斗', '一斗', 'イット', '西川'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-6',
                        'title': '鍾離',
                        'alt_text': '鍾離',
                        'caption': '鍾離',
                        'description': '鍾離',
                        'words': ['鍾離', 'ショウリ', 'モラクス'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-7',
                        'title': '申鶴',
                        'alt_text': '申鶴',
                        'caption': '申鶴',
                        'description': '申鶴',
                        'words': ['申鶴', 'シンカク'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-8',
                        'title': 'ショウ',
                        'alt_text': 'ショウ',
                        'caption': 'ショウ',
                        'description': 'ショウ',
                        'words': ['ショウ', '魈'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-9',
                        'title': '雷電将軍',
                        'alt_text': '雷電将軍',
                        'caption': '雷電将軍',
                        'description': '雷電将軍',
                        'words': ['雷電将軍', '雷電', 'ライデン'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-10',
                        'title': '楓原万葉',
                        'alt_text': '楓原万葉',
                        'caption': '楓原万葉',
                        'description': '楓原万葉',
                        'words': ['楓原万葉', '万葉', 'カズハ'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-11',
                        'title': '早柚',
                        'alt_text': '早柚',
                        'caption': '早柚',
                        'description': '早柚',
                        'words': ['早柚', 'サユ'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-12',
                        'title': '辛炎',
                        'alt_text': '辛炎',
                        'caption': '辛炎',
                        'description': '辛炎',
                        'words': ['辛炎', 'シンエン'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-13',
                        'title': '神里綾華',
                        'alt_text': '神里綾華',
                        'caption': '神里綾華',
                        'description': '神里綾華',
                        'words': ['神里綾華', '綾華', 'アヤカ'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-14',
                        'title': '宵宮',
                        'alt_text': '宵宮',
                        'caption': '宵宮',
                        'description': '宵宮',
                        'words': ['宵宮', 'ヨイミヤ'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-15',
                        'title': '重雲',
                        'alt_text': '重雲',
                        'caption': '重雲',
                        'description': '重雲',
                        'words': ['重雲', 'チョウウン'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-16',
                        'title': '主人公',
                        'alt_text': '主人公',
                        'caption': '主人公',
                        'description': '主人公',
                        'words': ['主人公', 'シュジンコウ'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-17',
                        'title': '珊瑚宮心海',
                        'alt_text': '珊瑚宮心海',
                        'caption': '珊瑚宮心海',
                        'description': '珊瑚宮心海',
                        'words': ['珊瑚宮心海', '心海', 'ココミ', 'ここみ'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-18',
                        'title': '刻晴',
                        'alt_text': '刻晴',
                        'caption': '刻晴',
                        'description': '刻晴',
                        'words': ['刻晴', 'コクセイ'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-19',
                        'title': '香菱',
                        'alt_text': '香菱',
                        'caption': '香菱',
                        'description': '香菱',
                        'words': ['香菱', 'シャンリン'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-20',
                        'title': '行秋',
                        'alt_text': '行秋',
                        'caption': '行秋',
                        'description': '行秋',
                        'words': ['行秋', 'ユキアキ'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-21',
                        'title': '胡桃',
                        'alt_text': '胡桃',
                        'caption': '胡桃',
                        'description': '胡桃',
                        'words': ['胡桃', 'フータオ'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-22',
                        'title': '九条裟羅',
                        'alt_text': '九条裟羅',
                        'caption': '九条裟羅',
                        'description': '九条裟羅',
                        'words': ['九条裟羅', '裟羅', 'サラ'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-23',
                        'title': '凝光',
                        'alt_text': '凝光',
                        'caption': '凝光',
                        'description': '凝光',
                        'words': ['凝光', 'ギョウコウ', 'ぎょうこう'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-24',
                        'title': '煙緋',
                        'alt_text': '煙緋',
                        'caption': '煙緋',
                        'description': '煙緋',
                        'words': ['煙緋', 'エンヒ', 'えんひ'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-25',
                        'title': '雲菫',
                        'alt_text': '雲菫',
                        'caption': '雲菫',
                        'description': '雲菫',
                        'words': ['雲菫', 'ウンチン', 'うんちん'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-26',
                        'title': 'レザー',
                        'alt_text': 'レザー',
                        'caption': 'レザー',
                        'description': 'レザー',
                        'words': ['レザー', 'れざー'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-27',
                        'title': 'リサ',
                        'alt_text': 'リサ',
                        'caption': 'リサ',
                        'description': 'リサ',
                        'words': ['リサ'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-28',
                        'title': 'モナ',
                        'alt_text': 'モナ',
                        'caption': 'モナ',
                        'description': 'モナ',
                        'words': ['モナ'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-29',
                        'title': 'パイモン',
                        'alt_text': 'パイモン',
                        'caption': 'パイモン',
                        'description': 'パイモン',
                        'words': ['パイモン'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-30',
                        'title': 'バーバラ',
                        'alt_text': 'バーバラ',
                        'caption': 'バーバラ',
                        'description': 'バーバラ',
                        'words': ['バーバラ'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-31',
                        'title': 'トーマ',
                        'alt_text': 'トーマ',
                        'caption': 'トーマ',
                        'description': 'トーマ',
                        'words': ['トーマ'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-32',
                        'title': 'タルタリヤ',
                        'alt_text': 'タルタリヤ',
                        'caption': 'タルタリヤ',
                        'description': 'タルタリヤ',
                        'words': ['タルタリヤ', 'もんじゃ', 'タルタリ', 'タルタル'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-33',
                        'title': 'スクロース',
                        'alt_text': 'スクロース',
                        'caption': 'スクロース',
                        'description': 'スクロース',
                        'words': ['スクロース'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-34',
                        'title': 'ゴロー',
                        'alt_text': 'ゴロー',
                        'caption': 'ゴロー',
                        'description': 'ゴロー',
                        'words': ['ゴロー'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-35',
                        'title': 'クレー',
                        'alt_text': 'クレー',
                        'caption': 'クレー',
                        'description': 'クレー',
                        'words': ['クレー'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-37',
                        'title': 'ガイア',
                        'alt_text': 'ガイア',
                        'caption': 'ガイア',
                        'description': 'ガイア',
                        'words': ['ガイア'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-38',
                        'title': 'エウルア',
                        'alt_text': 'エウルア',
                        'caption': 'エウルア',
                        'description': 'エウルア',
                        'words': ['エウルア'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-39',
                        'title': 'アンバー',
                        'alt_text': 'アンバー',
                        'caption': 'アンバー',
                        'description': 'アンバー',
                        'words': ['アンバー'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-40',
                        'title': 'アルベド',
                        'alt_text': 'アルベド',
                        'caption': 'アルベド',
                        'description': 'アルベド',
                        'words': ['アルベド'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-41',
                        'title': 'アーロイ',
                        'alt_text': 'アーロイ',
                        'caption': 'アーロイ',
                        'description': 'アーロイ',
                        'words': ['アーロイ'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-42',
                        'title': '八重神子',
                        'alt_text': '八重神子',
                        'caption': '八重神子',
                        'description': '八重神子',
                        'words': ['八重神子', '八重'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-43',
                        'title': 'ノエル',
                        'alt_text': 'ノエル',
                        'caption': 'ノエル',
                        'description': 'ノエル',
                        'words': ['ノエル', 'ノエラー'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-44',
                        'title': '北斗',
                        'alt_text': '北斗',
                        'caption': '北斗',
                        'description': '北斗',
                        'words': ['北斗', 'ホクト'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-45',
                        'title': 'フィッシュル',
                        'alt_text': 'フィッシュル',
                        'caption': 'フィッシュル',
                        'description': 'フィッシュル',
                        'words': ['フィッシュル', 'フィッシュ'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-46',
                        'title': 'ジン',
                        'alt_text': 'ジン',
                        'caption': 'ジン',
                        'description': 'ジン',
                        'words': ['ジン'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-47',
                        'title': 'ベネット',
                        'alt_text': 'ベネット',
                        'caption': 'ベネット',
                        'description': 'ベネット',
                        'words': ['ベネット', 'ベネ'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-48',
                        'title': '七七',
                        'alt_text': '七七',
                        'caption': '七七',
                        'description': '七七',
                        'words': ['七七', 'ナナ'],
                    },
                    {
                        'path': './data/genshin_imgs/sample.png',
                        'slug': 'img-49',
                        'title': 'ディルック',
                        'alt_text': 'ディルック',
                        'caption': 'ディルック',
                        'description': 'ディルック',
                        'words': ['ディルック'],
                    },
                ],
            }
        super().__init__(
            thread_list_url,
            thread_base_url,
            thread_titel_format,
            logs_dir,
            thd_soft_range,
            thd_soft_score_th,
            vectrize_model_name,
            k_class_model_path,
            soft_bans,
            hard_bans,
            topic_th,
            template_file_path,
            wordpress_url,
            wordpress_user,
            wordpress_password,
            wordpress_categorie_slugs,
            wordpress_tag_slugs,
            save_outputs=save_outputs,
            base_logs_dir=base_logs_dir,
            wordpress_default_page_status=wordpress_default_page_status,
            wordpress_default_featured_media_id=wordpress_default_featured_media_id,
            candidate_media_metas=candidate_media_metas,
            ng_word_file_title_path=ng_word_file_title_path,
            ng_word_file_page_path=ng_word_file_page_path,
            ng_word_file_parent_path=ng_word_file_parent_path,
            ng_word_file_keyphrase_path=ng_word_file_keyphrase_path,
            post_notification_url=post_notification_url,
            use_ng_title=use_ng_title,
            use_ng_content=use_ng_content,
            title_prefix=title_prefix,
            title_suffix=title_suffix,
            )
